### ISSUE TITLE
Get starting with testing of SLAM-Super-6D

### ISSUE THREAD

**Issue by HripsimeS** [520xyxyzq/slam-super-6d#7]
@520xyxyzq @keevindoherty 

First of all, congratulations with your publication and great project!!!
I would like to know more details about how to use the inference mode and which file is exactly dedicated to training. 

I have installed pre-commit on my conda enviroment and the version is 2.20.0. Can you please send me more details about the steps I need to do in order to get started using pre-commit with the codebase. For the moment when I run "pre-commit install" on my Command Prompt I can see the following message only: 

An error has occurred: FatalError: git failed. Is it installed, and are you in a Git repository directory?
Check the log at C:\Users\Hripsime\.cache\pre-commit\pre-commit.log

Look forward to hearing from you!

**Comment by 520xyxyzq** [comment]
Hi, Hripsime, thank you for your interest in our work. We are excited to hear that you are trying out our code!!

Sorry about the confusion on installations. We added [installation instructions](https://github.com/520xyxyzq/slam-super-6d#installing) in ReadMe to make it easier for folks to install dependencies.

For `pre-commit`, we only use it for auto-linting. If you don't plan to commit changes to the code, there is no need to install it. But if you plan to suggest changes to our code (which you are very welcome to do :-), you should be able to install it by following the steps on [pre-commit.com](https://pre-commit.com/). I'm not sure what exactly caused the error you encountered. I get the same error usually when I'm not running `pre-commit install` inside the `/path/to/slam-super-6d`.

Thank you for your question on how to run the training and inference code. Our method provides pseudo training data to fine-tune 6D object pose estimators, but it's _not_ designed to be a fully differentiable pipeline. The only trainable part would be the object pose estimator itself. But the benefit is that our method can work with most learning-based object pose estimators. Given a sequence of unlabeled images, if we have a pre-trained pose estimator and the camera odometry, we can generate pseudo ground truth labels by running:

```
cd /path/to/slam-super-6d
python3 src/pseudo_labeler.py --joint --mode 1 --dets /paths/to/obj/pose/predictions --odom /path/to/odometry --out /path/to/save/output/files
```
(The input and output poses are all stored in .txt files following the [TUM format](https://vision.in.tum.de/data/datasets/rgbd-dataset/file_formats))

In our experiments, we used NVIDIA DOPE as our initial estimator. If you are interested in testing out the DOPE estimator before and after self-training on the YCB-v dataset, we saved the weights files [here](https://drive.google.com/drive/folders/1fkMdr9Y8ls2EQTLtDmy8dULPHMEHWKKs?usp=sharing). You can save the weight(s) to your favorite folder, change [here](https://github.com/520xyxyzq/slam-super-6d/blob/645701adaf80a273c10adb863878d8f6af228f61/experiments/ycbv/inference/config_inference/config_pose.yaml#L11) to point to the weight file, and run the inference code by:

```
python3 experiments/ycbv/inference/inference.py --data /path/to/image/folder/ --outf /path/to/save/pose/predictions
```

More details about how to run/train DOPE networks can be found [here](https://github.com/NVlabs/Deep_Object_Pose/tree/master/scripts/train2) in the DOPE Github repo. You can also find more details about our YCB-V experiments [here](https://github.com/520xyxyzq/slam-super-6d/tree/main/experiments/ycbv).

**Comment by 520xyxyzq** [comment]
Hi, Hripsime, the input argument `data` should be an image _folder_. The script will read all the `.png` and `.jpg` files in the folder, sort them by names, estimate the pose of the target object (cracker in this case) in the image, and save it to a txt file. That said, you should be able to fix it by changing `C:/SLAM/image/image3.jpg` to `C:/SLAM/image/`, and you will see this `C:/SLAM/output/0000.txt` file with the predicted poses. (If the cracker box is not in the image or the estimator fails to predict its pose, the corresponding line will be timestamp + 7 `0.0000`)

**Comment by HripsimeS** [comment]
@520xyxyzq thanks for your quick reply!! In "config_pose.yaml" file I changed the weight with cracker self-trained pre-trainied model (you can find a screenshot below), in my "image" folder I placed 3 .jpg files of cracker boxes, I changed the input all "image folder", but when I run the inference code I received the same error please find below. Any ideas what is going on? 

![pose](https://user-images.githubusercontent.com/42246765/189834369-02f97116-e51a-4ed8-8675-bd18835a8eb8.png)
![slam-bug](https://user-images.githubusercontent.com/42246765/189834377-0d534fbb-0606-43d7-9e0a-52f117569cd6.png)

**Comment by 520xyxyzq** [comment]
Hi, Hripsime, thank you for the question and that was a good catch! I thought `inference.py` was reading both `png` and `jpg` files in the folder but it was only reading `png` files. I modified the script so it can read both types of files now. You can `git pull` the change to your local machine, and you should be able to run the script now.

**Comment by HripsimeS** [comment]
@520xyxyzq Hi Ziqi. Thanks a lot for fixing it, now it works on both formats :) 
Next step for me is to undesrtand how to make a real time 3D object detection with camera. I saw you used ORB-SLAM3 camera for your experiments to do a real time detection of objects. I have "Intel RealSense LiDAR Camera L515" and I was wondering if possible to use it with your method. If yes, can you please send more details how I can do a real time 3D object detection with IntelRealSense camera (I will use examples for cracker/sugar boxes). Look forward to hearing from you!!

**Comment by 520xyxyzq** [comment]
Will close this for now and please feel free to follow up.
