### ISSUE TITLE
A question about your paper

### ISSUE THREAD

**Issue by pyni** [520xyxyzq/slam-super-6d#8]
您好，我是slam的初学者，对您的论文很感兴趣。
对于您论文里的一些名词有些疑问想请教一下。
据我了解，位姿图优化（PGO）是只优化位姿，路标点只作为优化过程中的约束；而BA优化是联合优化位姿和路标点。

但是根据论文的优化目标，以及图1中的（d）可以看出，优化的目标不仅仅有路标点（l），而且有位姿（x）。而全文一直在用PGO来称呼这个优化过程。请问为什么不应该是用bundle adjustment来称呼呢？谢谢！

**Comment by 520xyxyzq** [comment]
感谢您的问题！您说的很对，在 pose-graph SLAM的语境下，PGO 是一般只优化机器人位姿，由于这种应用场景的广泛性，在很多情况下我们都交换使用 pgo 和 pose-graph SLAM 这两个词。但是我对 PGO 的理解是 它是 variables 和 constraints 都是 pose 的 factor graph optimization， 而这些 variables 不一定都是机器人 pose。比如在 [object-based SLAM](https://github.com/520xyxyzq/awesome-object-SLAM) 的语境下, 我们也称包含 object pose 的 graph optimization 为 PGO，例如 [SLAM++](https://www.doc.ic.ac.uk/~ajd/Publications/salas-moreno_etal_cvpr2013.pdf)。您说这个应该称为 BA，这也是非常正确的一种叫法，比如 [cosypose](https://arxiv.org/abs/2008.08465) 就在使用 object level bundle adjustment 来描述同一件事情。不知道这是否回答了您的问题。

**Comment by pyni** [comment]
好的，谢谢，非常感谢您及时的回答
